### ISSUE TITLE
Brak UpgradeShop.yml

### ISSUE THREAD

**Issue by TosneX** [ScreamingSandals/SimpleGuiFormat#5]
**Describe the bug**
Gdy spojrzałem wpliki nie było upgradeShop.yml albo jakoś tak

**Server and plugin version**
Spigot version:
Scraming BedWars 1.9-16 chyba ta

**Installed plugins on server (can be obtained by `/pl`):**

**Console log:**

**Configuration (of <gui>.yml):**
Brakuje UpgradeShop.yml prosze pomóżcie

**Comment by zlataovce** [comment]
Please write in english and provide complete info.
