### ISSUE TITLE
download Please

### ISSUE THREAD

**Issue by RangeBanenge** [ScreamingSandals/SimpleGuiFormat#9]
download Please

**Comment by RangeBanenge** [comment]
my kernel is paper 1.12.2

**Comment by Misat11** [comment]
SimpleInventories is a library which is already bundled in BedWars and is used for reading the shop file, you were just supposed to look at the format to change your shop.yml. Please stop creating useless issues or I'm gonna block you from the organisation.

**Comment by RangeBanenge** [comment]
Sorry, I just don't know much English, and I know what placeholders are.


сб, 1 апр. 2023 г. в 11:56, Misat11 ***@***.***>:

**Comment by Misat11** [comment]
The explanation of placeholders were directed at someone else who used one of your issues to ask what placeholders are.

**Comment by RangeBanenge** [comment]
Yes ... I only realized this when I sent the message .. that's what it
means first you need to think


сб, 1 апр. 2023 г. в 12:35, Misat11 ***@***.***>:
